#!/usr/bin/env bash
# dead-skills-report.sh — list local skills with zero recorded invocations
# in skill-invocations.jsonl, plus directory mtime so the auto-prune wrapper
# can apply the grace period.
#
# Output: $AGENT_HOME/logs/dead-skills-latest.md
# Echoes the report path on stdout for the caller.

set -u

AGENT_HOME="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="$AGENT_HOME/skills"
SINK="$AGENT_HOME/telemetry/skill-invocations.jsonl"
DATE="$(date +%F)"
REPORT="$AGENT_HOME/logs/dead-skills-latest.md"
mkdir -p "$(dirname "$REPORT")" 2>/dev/null || true

{
  echo "# Dead skills report — $DATE"
  echo
  echo "Generated by adapters/codex/scripts/dead-skills-report.sh."
  echo "Skills listed below have zero invocations recorded in \`telemetry/skill-invocations.jsonl\`."
  echo
  echo "| Skill | Last modified (mtime) |"
  echo "|---|---|"
} > "$REPORT"

if [ -d "$SKILLS_DIR" ]; then
  # Iterate local skill directories (skip _archived).
  for d in "$SKILLS_DIR"/*/; do
    [ -d "$d" ] || continue
    name="$(basename "$d")"
    [ "$name" = "_archived" ] && continue
    count=0
    if [ -f "$SINK" ]; then
      count="$(grep -c "\"skill\":\"$name\"" "$SINK" 2>/dev/null || echo 0)"
    fi
    if [ "$count" = "0" ]; then
      # Portable mtime: stat fallback for both BSD and GNU.
      mtime="$(stat -c '%y' "$d" 2>/dev/null || stat -f '%Sm' "$d" 2>/dev/null || echo 'unknown')"
      printf '| %s | %s |\n' "$name" "$mtime" >> "$REPORT"
    fi
  done
else
  echo "_(no skills directory at $SKILLS_DIR)_" >> "$REPORT"
fi

echo "$REPORT"
exit 0
