#!/usr/bin/env bash
# adapters/cursor/scripts/cursor-weekly-report.sh — scheduled by install-cron.sh.
#
# Cursor cannot spawn an AI binary non-interactively for auto-prune (no headless
# Cursor CLI as of v0.2). Instead, this script runs dead-skills-report.sh and
# appends the output as a dated memory file the user reviews on next session.
#
# Idempotent per-day: if today's report already exists, the script appends a
# delimiter and updates it instead of creating duplicates.

set -u

AGENT_HOME="$(cd "$(dirname "$0")/.." && pwd)"
REPORT_SCRIPT="$AGENT_HOME/scripts/dead-skills-report.sh"
DATE="$(date +%F)"
OUT="$AGENT_HOME/memory/feedback/dead-skills-report-$DATE.md"

mkdir -p "$(dirname "$OUT")" 2>/dev/null || true

REPORT="$("$REPORT_SCRIPT" 2>&1 || true)"
TS="$(date -u +%FT%TZ)"

if [ -f "$OUT" ]; then
  {
    printf '\n---\n\n## Re-run %s\n\n' "$TS"
    printf '%s\n' "$REPORT"
  } >> "$OUT"
else
  {
    printf '# Weekly dead-skills report — %s\n\n' "$DATE"
    printf 'Generated by `adapters/cursor/scripts/cursor-weekly-report.sh` on %s.\n\n' "$TS"
    printf 'Cursor has no auto-prune (no headless binary). Review this report,\n'
    printf 'archive truly-unused skills under `skills/_archived/`, and update\n'
    printf 'the router rules under `.cursor/rules/` to remove their entries.\n\n'
    printf '## Report\n\n%s\n' "$REPORT"
  } > "$OUT"
fi

exit 0
