#!/usr/bin/env bash
# adapters/gemini-cli/scripts/gemini-weekly-report.sh — scheduled by install-cron.sh.
#
# Gemini CLI has no SessionEnd shell hook and no documented way to spawn the CLI
# non-interactively for an autonomous auto-prune. Instead, this script runs
# dead-skills-report.sh and appends the output as a dated log file in logs/
# (NOT memory/ — the brain holds curated knowledge only) the user reviews on
# their next session.
#
# It passes --target explicitly because dead-skills-report.sh auto-detects the
# agent home by looking for an AGENTS.md sibling; the Gemini adapter's identity
# file is GEMINI.md, so the auto-detect would otherwise miss.
#
# Idempotent per-day: if today's report already exists, the script appends a
# delimiter and updates it instead of creating duplicates.

set -u

AGENT_HOME="$(cd "$(dirname "$0")/.." && pwd)"
REPORT_SCRIPT="$AGENT_HOME/scripts/dead-skills-report.sh"
DATE="$(date +%F)"
OUT="$AGENT_HOME/logs/dead-skills-report-$DATE.md"

mkdir -p "$(dirname "$OUT")" 2>/dev/null || true

REPORT="$("$REPORT_SCRIPT" --target "$AGENT_HOME" 2>&1 || true)"
TS="$(date -u +%FT%TZ)"

if [ -f "$OUT" ]; then
  {
    printf '\n---\n\n## Re-run %s\n\n' "$TS"
    printf '%s\n' "$REPORT"
  } >> "$OUT"
else
  {
    printf '# Weekly dead-skills report — %s\n\n' "$DATE"
    printf 'Generated by `adapters/gemini-cli/scripts/gemini-weekly-report.sh` on %s.\n\n' "$TS"
    printf 'Gemini CLI has no auto-prune (no SessionEnd hook, no headless prune binding).\n'
    printf 'Review this report, archive truly-unused skills under `skills/_archived/`,\n'
    printf 'and trim their rows from the Skill Router table in `GEMINI.md`.\n\n'
    printf '## Report\n\n%s\n' "$REPORT"
  } > "$OUT"
fi

exit 0
